name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 18 * * *" # Tự động cập nhật mỗi ngày
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write # 👈 Cấp quyền trực tiếp tại đây để không bị lỗi 403

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME: radical
